# SPDX-FileCopyrightText: 2024 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name = 'Visual Studio Code'
type = 'directory' # md
about = '''
A theme for [Visual Studio Code](https://code.visualstudio.com).
''' # rhai

display = 'arrangement + " – " + scheme("main")' # rhai
nomenclature = '''
let scheme = "";
for word in `${scheme("main")}`.split() { scheme += word.to_lower() + '-' }
arrangement_id + if scheme.pop() == () { () } else { '.' + scheme }
'''

subdirectories = ['.vscode']

[options]
accent   = { name =   'Accent', default.set = 'any' }
emphasis = { name = 'Emphasis', default.set = 'cyan' }

# TODO contrast-border = { default = -2.0 }

[options.dim-border]
name = 'Inactive border color'
about = 'Use another color for the window border when it is out of focus'
default = true

[options.dim-header]
name = 'Inactive title bar color'
about = 'Use another color for the title bar when the window is out of focus'
default = true

[options.semantic-highlighting]
name = 'Semantic Highlighting'
default = true

[options.terminal-bold]
name = 'Swaps the roles “like” and “area” for terminal emphasis colors'
about = 'It is better if the bold text uses intense colors'
default = true

[schemes]
common = { name = 'Common', fallback = 'main' }
main   = { name = 'Main' }

activity-bar = { fallback = 'main', name = 'Activity Bar' }
menu         = { fallback = 'main', name = 'Menu' }
status-bar   = { fallback = 'main', name = 'Status Bar' }
terminal     = { fallback = 'main', name = 'Terminal' }

breadcrumb = { fallback = 'common', name = 'Breacrumb' }
editor     = { fallback = 'common', name = 'Editor' }
side-bar   = { fallback = 'common', name = 'Side Bar' }
tab-bar    = { fallback = 'common', name = 'Tab Bar' }
title-bar  = { fallback = 'common', name = 'Title Bar' }

notification = { fallback = 'editor', name = 'Notification' }
welcome-page = { fallback = 'editor', name = 'Welcome Page' }

[suggested-paths]
vscode-oss = { home = '.vscode-oss/extensions' }
vscodium-flatpak = { home = '.var/app/com.vscodium.codium/data/codium/extensions' }

[files]
manifest = { name = 'package.json' }
theme    = { name = 'color-theme.json' }
launch   = { name = 'launch.json', at = 1 }
