# SPDX-FileCopyrightText: 2024 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name = 'Visual Studio Code Settings'
type = 'text-file' # md
about = '''
A JSON piece that configures the following extensions
for [Visual Studio Code](https://code.visualstudio.com'):

– [Comment Anchors](https://github.com/StarlaneStudios/vscode-comment-anchors).

– [LaTeX Workshop](https://github.com/James-Yu/LaTeX-Workshop).
'''

[schemes]
editor = { name = 'Editor' }

[suggested-paths]
default = { default = 'vscode-settings.json' }
temporary = { temporary = 'vscode-settings.json' }
