# SPDX-FileCopyrightText: 2024 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name = 'Visual Studio Code Settings'
type = 'text-file' # xml
about = """
A JSON piece that configures the following extensions for \
<a href='https://code.visualstudio.com'>Visual Studio Code</a>:

– <a href='https://github.com/StarlaneStudios/vscode-comment-anchors'>Comment Anchors</a>.
– <a href='https://github.com/James-Yu/LaTeX-Workshop'>LaTeX Workshop</a>.
"""

[schemes]
editor = { name = 'Editor' }

[suggested-paths]
default = { default = 'vscode-settings.json' }
temporary = { temporary = 'vscode-settings.json' }

[script] # rhai
embedded = '''
const editor = cfg::scheme("editor");

const dark = editor.lower.text.luma() > editor.lower.like.luma();

fn out() { `"#${this.to_hex_rgb(true)}"` } // json

fn shadow() {
	const L = this.luma();
	`"#${0xFF.fade(2 ** -L + 0.2 * L - 0.6).to_hex_rgba(true)}"`
}

`{
	"commentAnchors.tags.anchors": {
		"ANCHOR:": {
			"iconColor": ${editor.lower.text.out()},
			"highlightColor": ${editor.lower.text.out()},
			"isItalic": false,
			"scope": "file"
		},
		"REMOVE": {
			"iconColor": ${editor.red.like.out()},
			"highlightColor": ${editor.red.like.out()},
			"isItalic": false,
			"scope": "workspace"
		},
		"BUG": {
			"iconColor": ${editor.red.like.out()},
			"highlightColor": ${editor.red.like.out()},
			"isItalic": false,
			"scope": "workspace"
		},
		"WARNING": {
			"iconColor": ${editor.yellow.like.out()},
			"highlightColor": ${editor.yellow.like.out()},
			"isItalic": false,
			"scope": "workspace"
		},
		"WATCH": {
			"iconColor": ${editor.green.like.out()},
			"highlightColor": ${editor.green.like.out()},
			"isItalic": false,
			"scope": "workspace",
			"behavior": "link"
		},
		"TODO": {
			"iconColor": ${editor.cyan.like.out()},
			"highlightColor": ${editor.cyan.like.out()},
			"isItalic": false,
			"scope": "workspace"
		},
		"FIXME": {
			"iconColor": ${editor.yellow.like.out()},
			"highlightColor": ${editor.yellow.like.out()},
			"isItalic": false,
			"scope": "workspace"
		},
		"HACK": {
			"iconColor": ${editor.magenta.like.out()},
			"highlightColor": ${editor.magenta.like.out()},
			"isItalic": false,
			"scope": "workspace"
		},
		"NOTE": {
			"iconColor": ${editor.blue.like.out()},
			"highlightColor": ${editor.blue.like.out()},
			"isItalic": false,
			"scope": "file"
		},
		"SECTION": {
			"iconColor": ${editor.any.text.out()},
			"highlightColor": ${editor.any.text.out()},
			"isItalic": false,
			"scope": "workspace",
			"behavior": "region"
		}
	},
	
	"latex-workshop.view.pdf.color.dark.backgroundColor": ${editor.lower.like.out()},
	"latex-workshop.view.pdf.color.dark.pageBorderColor": ${editor.lower.like.shadow()},
	"latex-workshop.view.pdf.color.dark.pageColorsBackground": ${editor.upper.like.out()},
	"latex-workshop.view.pdf.color.dark.pageColorsForeground": ${editor.lower.text.out()},
	"latex-workshop.view.pdf.color.light.backgroundColor": ${editor.lower.like.out()},
	"latex-workshop.view.pdf.color.light.pageBorderColor": ${editor.lower.like.shadow()},
	"latex-workshop.view.pdf.color.light.pageColorsBackground": ${editor.lower.area.out()},
	"latex-workshop.view.pdf.color.light.pageColorsForeground": ${editor.lower.text.out()}
}`
'''
