# SPDX-FileCopyrightText: 2024 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name = 'Firefox GNOME Theme (v166)'
type = 'text-file' # md
about = '''
Custom colors for [Firefox GNOME theme](https://github.com/rafaelmardojai/firefox-gnome-theme).
'''

schemes.main.name = 'Main'

[options]
accent  = { name = 'Accent' , default.set = 'any' }
private = { name = 'Private', default.set = 'magenta' }

[options.dim-header]
name = 'Inactive header bar colors'
about = 'Use another color for the header bar when the window is out of focus'
default = true

[suggested-paths]
default = { default = 'firefox/customChrome.css' }
flatpak = { home = '.var/app/org.mozilla.firefox/.mozilla/aquarelle/customChrome.css' }
user    = { home = '.mozilla/aquarelle/customChrome.css' }
