# SPDX-FileCopyrightText: 2024 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name = 'Firefox'
type = 'text-file' # md
about = '''
Style sheet for [Firefox Web Browser](https://mozilla.org/en-US/firefox).
'''

schemes.main.name = 'Main'

[options]
accent = { name = 'Accent', default.set = 'any' }

[suggested-paths]
default = { default = 'firefox/userContent.css' }
flatpak = { home = '.var/app/org.mozilla.firefox/.mozilla/aquarelle/userContent.css' }
user    = { home = '.mozilla/aquarelle/userContent.css' }
