# SPDX-FileCopyrightText: 2023 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

 name = 'Ableton Live'
 type = 'text-files'
about = """
An experimental XML file that provides a theme for \
<a href='https://www.ableton.com/en/live'>Ableton Live</a>, a digital audio workstation.

On Linux with Wine it should be linked to a path like:
<tt>~/.wine/drive_c/ProgramData/Ableton/Live 11 Suite/Resources/Themes/my_theme.xml</tt>
"""

displaying = '`${arrangement} – ${scheme("main")}`'
    naming = '`${arrangement} – ${scheme("main")}`'
 extension = '.ask'

[schemes]
main = { name = 'Main Color Scheme' }

[options]
accent = { name = 'Accent Color Set', default.set = 'any' }

[suggested-paths]
default = { default = 'ableton-live' }
