# SPDX-FileCopyrightText: 2024 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name = 'Aquarelle'
about = 'The original namespace of the application'

[maps]
adwaita = { manifest = 'adwaita.toml', script = 'adwaita.rhai' }
blackbox = { manifest = 'blackbox.toml', script = 'blackbox.rhai' }
chromium = { manifest = 'chromium.toml', script = 'chromium.rhai' }
code-settings = { manifest = 'code/settings.toml', script = 'code/settings.rhai' }
code = { manifest = 'code/map.toml', script = 'code/map.rhai' }
css-colors = { manifest = 'css_colors.toml', script = 'css_colors.rhai' }
dark-reader = { manifest = 'dark_reader.toml', script = 'dark_reader.rhai' }
firefox-gnome-theme = { manifest = 'firefox/gnome_theme.toml', script = 'firefox/gnome_theme.rhai' }
firefox = { manifest = 'firefox/map.toml', script = 'firefox/map.rhai' }
ghostwriter = { manifest = 'ghostwriter.toml', script = 'ghostwriter.rhai' }
gimp-palette = { manifest = 'gimp_palette.toml', script = 'gimp_palette.rhai' }
jdownloader = { manifest = 'jdownloader.toml', script = 'jdownloader.rhai' }
konsole = { manifest = 'konsole.toml', script = 'konsole.rhai' }
obsidian-border = { manifest = 'obsidian-border.toml', script = 'obsidian-border.rhai' }
plasma-scheme = { manifest = 'plasma_scheme.toml', script = 'plasma_scheme.rhai' }
qjackctl = { manifest = 'qjackctl.toml', script = 'qjackctl.rhai' }
reaper = { manifest = 'reaper/map.toml', script = 'reaper/map.rhai' }
sidebery = { manifest = 'sidebery.toml', script = 'sidebery.rhai' }
syntax-highlighting = { manifest = 'syntax_highlighting.toml', script = 'syntax_highlighting.rhai' }
telegram-desktop = { manifest = 'telegram_desktop.toml', script = 'telegram_desktop.rhai' }
wine = { manifest = 'wine.toml', script = 'wine.rhai' }
zotero = { manifest = 'zotero.toml', script = 'zotero.rhai' }

[schemes]
neon-cake = { manifest = 'schemes/neon_cake.toml', script = 'schemes/neon_cake.rhai' }

[themes]
everforest = 'themes/everforest.toml'
gruvbox    = 'themes/gruvbox.toml'
neon-cake  = 'themes/neon_cake.toml'
solarized  = 'themes/solarized.toml'
