# SPDX-FileCopyrightText: 2024 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name = 'Black Box & Tilix'
type = 'text-file' # md
about = '''
A JSON file that provides a color scheme for the terminal emulators
[Black Box](https://gitlab.gnome.org/raggesilver/blackbox)
and [Tilix](https://gnunn1.github.io/tilix-web).

I recommend trying the bold option if your terminal uses intense colors for bold text.
''' # rhai

display = 'arrangement + " – " + scheme("main") + ".json"' # rhai
nomenclature = '''
let scheme = "";
for word in `${scheme("main")}`.split() { scheme += word.to_lower() + '-' }
arrangement_id + if scheme.pop() == () { () } else { '.' + scheme }
'''

[options]
accent = { name = 'Accent', default.set = 'any' }

[options.bold]
name = 'Swaps the roles “like” and “area” for emphasis colors'
about = 'It is better if the bold text uses intense colors'
default = false

[schemes]
main = { name = 'Main' }

[suggested-paths]
default = { default = 'blackbox' }

black-box-1       = { data = 'blackbox/schemes' }
black-box-2       = { home = '.local/share/blackbox/schemes' }
black-box-flatpak = { home = '.var/app/com.raggesilver.BlackBox/data/blackbox/schemes' }

tilix-1 = { config = 'tilix/schemes' }
tilix-2 = { home = '.config/tilix/schemes' }
