# SPDX-FileCopyrightText: 2023 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

 name = 'Black Box & Tilix'
 type = 'text-files'
about = """
A JSON file that provides a color scheme for the terminal emulators \
<a href='https://gitlab.gnome.org/raggesilver/blackbox'>Black Box</a> \
and <a href='https://gnunn1.github.io/tilix-web'>Tilix</a>.

I recommend trying the bold option if your terminal uses intense colors for bold text.
"""

displaying = '`${arrangement} – ${scheme("main")}`'

naming = '''
	let scheme = "";
	
	for word in `${scheme("main")}`.split()
	{ scheme += `${word.to_lower()}-` }
	
	if scheme.pop() == () { arrangement_id }
	else { `${arrangement_id}-${scheme}` }
'''

extension = '.json'

[schemes]
main = { name = 'Main Color Scheme' }

[options]
accent = { name = 'Accent Color Set', default.set = 'any' }

[options.bold]
   name = 'Swaps the roles “like” and “area” for emphasis colors'
  about = 'It is better if the bold text uses intense colors'
default = false

[suggested-paths]
default = { default = 'blackbox_and_tilix' }

# Black Box:
black-box-flatpak = { home = '.var/app/com.raggesilver.BlackBox/data/blackbox/schemes' }
black-box-1       = { data = 'blackbox/schemes' }
black-box-2       = { home = '.local/share/blackbox/schemes' }

# Tilix:
tilix-1 = { config = 'tilix/schemes' }
tilix-2 = { home = '.config/tilix/schemes' }
