# SPDX-FileCopyrightText: 2024 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name = 'Dark Reader'
type = 'text-file' # xml
about = """
A JSON file that configures the extension \
<a href='https://github.com/darkreader/darkreader'>Dark Reader</a>.

You can import it from the extension, but be careful about \
overwriting your current preferences with the ones in this map.
""" # rhai

display      = 'arrangement + " – " + scheme("main")' # rhai
nomenclature = 'arrangement + " – " + scheme("main") + ".json"'

schemes.main.name = 'Main'

[options]
accent = { default.accent = 'any', name = 'Accent' }

detection  = { default = false, name = 'Detect Dark Theme' }
menus      = { default = false, name = 'Enable Context Menus' }
sync       = { default = true , name = 'Sync Settings' }
sync-fixed = { default = false, name = 'Sync Fixed Sites' }
theme      = { default = false, name = 'Change Browser Theme' }

[options.exclusions]
name = 'Site exclusion list (domains in quotes separated by commas)'
about = 'No comma at end, e.g. "web.whatsapp.com", "www.google.com"'
default = '"web.whatsapp.com"'

[options.inclusions]
name = 'Site inclusion list (like the exclusions)'
about = 'For sites disabled by default, e.g. "vscodethemes.com"'
default = ''

[options.listed-only]
name = 'Apply to listed only'
about = 'The exclusion list becomes a white list'
default = false

[suggested-paths]
default = { default = 'dark_reader' }

[script] # rhai
embedded = '''
const main = cfg::scheme("main");

fn out() { '#' + this.to_hex_rgb(true) } // json

`{
	"enabled": true,
	"fetchNews": true,
	
	"theme": {
		"mode": ${if main.lower.text.luma() > main.lower.like.luma() { 1 } else { 0 }},
		"brightness": 100,
		"contrast": 100,
		"grayscale": 0,
		"sepia": 0,
		"useFont": false,
		"fontFamily": "Open Sans",
		"textStroke": 0,
		"engine": "dynamicTheme",
		"stylesheet": "",
		"darkSchemeBackgroundColor": "${main.lower.like.out()}",
		"darkSchemeTextColor": "${main.lower.text.out()}",
		"lightSchemeBackgroundColor": "${main.lower.area.out()}",
		"lightSchemeTextColor": "${main.lower.text.out()}",
		"scrollbarColor": "auto",
		"selectionColor": "${main[cfg::option("accent")].area.out()}",
		"styleSystemControls": false,
		"lightColorScheme": "Default",
		"darkColorScheme": "Default",
		"immediateModify": false
	},
	
	"presets": [],
	"customThemes": [],
	
	"siteList": [${cfg::option("exclusions")}],
	
	"siteListEnabled": [${cfg::option("inclusions")}],
	
	"applyToListedOnly": ${cfg::option("listed-only")},
	"changeBrowserTheme": ${cfg::option("theme")},
	"syncSettings": ${cfg::option("sync")},
	"syncSitesFixes": ${cfg::option("sync-fixed")},
	
	"automation": {
		"enabled": false,
		"mode": "",
		"behavior": "OnOff"
	},
	
	"time": {
		"activation": "18:00",
		"deactivation": "9:00"
	},
	
	"location": {
		"latitude": null,
		"longitude": null
	},
	
	"previewNewDesign": true,
	"enableForPDF": true,
	"enableForProtectedPages": false,
	"enableContextMenus": ${cfg::option("menus")},
	"detectDarkTheme": ${cfg::option("detection")},
	"automationBehaviour": "OnOff"
}`
'''
