# SPDX-FileCopyrightText: 2024 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name = 'ghostwriter'
type = 'text-file' # md
about = '''
A JSON file that defines a color theme for the [ghostwriter] text editor.
[ghostwriter]: https://github.com/KDE/ghostwriter
''' # rhai

nomenclature = 'arrangement + " – " + scheme("main") + ".json"'

[schemes]
light.name = 'Light'
 dark.name = 'Dark'

[suggested-paths]
default = { default = 'ghostwriter' }
flatpak = { home = '.var/app/io.github.wereturtle.ghostwriter/data/ghostwriter/themes' }
user-1  = { config = 'ghostwriter/themes' }
user-2  = { home = '.config/ghostwriter/themes' }
