# SPDX-FileCopyrightText: 2024 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name = 'Konsole'
type = 'text-file' # md
about = '''
An INI file that provides a color scheme for
[Konsole](https://konsole.kde.org), a KDE terminal emulator.
''' # rhai

display      = 'arrangement + " – " + scheme("main")' # rhai
nomenclature = 'arrangement + " – " + scheme("main") + ".colorscheme"'

schemes.main.name = 'Main'

[options]
blur    = { name = 'Background Blur', default = false }
opacity = { name = 'Background Opacity', default = 1.0 }

[options.bold]
name = 'Swaps the roles “like” and “area” for emphasis colors'
about = 'It is better if the bold text uses intense colors'
default = false

[options.embedded]
name = 'Use the “mid” color set instead of “low” for backgrounds' # FIXME
about = 'Useful for matching background colors when Konsole is “embedded”'
default = false

[suggested-paths]
default = { default = 'konsole' }
user-1  = { data = 'konsole' }
user-2  = { home = '.local/share/konsole' }
