# SPDX-FileCopyrightText: 2023 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

 name = 'Plasma Color Scheme'
 type = 'text-files'
about = """
A KDE Plasma Color Scheme focused on the visual styles \
<a href='https://invent.kde.org/plasma/breeze'>Breeze</a> \
and <a href='https://github.com/boehs/Lightly'>Lightly</a>.
"""

displaying = '`${arrangement} – ${scheme("main")}`'
    naming = '`${arrangement} – ${scheme("main")}`'
 extension = '.colors'

[options]
accent = { default.set = 'any', name = 'Accent Color Set' }

[options.dim-header]
   name = 'Inactive header color'
  about = 'Use another color for headers when the window is out of focus'
default = true

[options.dim-selection]
   name = 'Inactive selection color'
  about = 'Dim the selection color for out-of-focus windows or views'
default = true

[options.lightly]
   name = 'Lightly Mode'
  about = 'Optimize Scheme for Lightly Style'
default = false

[options.opacity]
   name = 'Window opacity'
  about = 'Better with the Lightly style'
default = 1.0

[schemes.main]
 name = 'Main Color Scheme'
about = 'Used for non-dark parts of windows'

[schemes.complementary]
    name = 'Complementary Color Scheme'
   about = 'Used for dark parts of windows'
fallback = 'main'

[suggested-paths]
default = { default = 'breeze_style' }
 user-1 = { data = 'color-schemes' }
 user-2 = { home = '.local/share/color-schemes' }
