# SPDX-FileCopyrightText: 2024 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name = 'QjackCtl'
type = 'text-file' # md
about = '''
An INI file that provides a color scheme for
[QjackCtl](https://qjackctl.sourceforge.io).
''' # rhai

display      = 'arrangement + " – " + scheme("main")' # rhai
nomenclature = 'arrangement + " – " + scheme("main") + ".conf"'

schemes.main.name = 'Main'

[options]
accent = { name = 'Accent', default.set = 'any' }

[suggested-paths]
default = { default = 'qjackctl' }
