# SPDX-FileCopyrightText: 2023 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

 name = 'Sidebery'
 type = 'text-files'
about = 'A CSS file for the extension <a href="https://github.com/mbnuqw/sidebery">Sidebery</a>.'

displaying = '`${arrangement} – ${scheme("main")}`'
    naming = '`${arrangement} – ${scheme("main")}`'
 extension = '.css'

[schemes]
main = { name = 'Main Color Scheme' }

[options]
accent = { default.set = 'any', name = 'Accent Color Set' }

[suggested-paths]
default = { default = 'sidebery' }
