# SPDX-FileCopyrightText: 2024 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name = 'Sidebery'
type = 'text-file' # md
about = '''
A CSS file for the extension
[Sidebery](https://github.com/mbnuqw/sidebery).
''' # rhai

display = 'arrangement + " – " + scheme("main")' # rhai
nomenclature = 'arrangement + " – " + scheme("main") + ".css"'

schemes.main.name = 'Main'

[options]
accent = { name = 'Accent', default.set = 'any' }

[suggested-paths]
default = { default = 'sidebery' }
