# SPDX-FileCopyrightText: 2024 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name = 'KDE Syntax Highlighting'
type = 'text-file' # xml
about = """
A JSON file that provides a <a href='https://docs.kde.org/trunk5/en/kate/katepart/color-themes.html'>color theme</a> \
for KDE's <a href='https://api.kde.org/frameworks/syntax-highlighting/html/index.html'>Syntax Highlighting</a> \
framework, used by applications such as KWrite, Kate, and KDevelop.
""" # rhai

display = 'arrangement' # rhai
nomenclature = 'arrangement_id + ".theme"'

schemes.main.name = 'Main'

[suggested-paths]
default = { default = 'syntax_highlighting' }
data    = { data = 'org.kde.syntax-highlighting/themes' }

[script] # rhai
embedded = '''
const main = cfg::scheme("main");

const dark = main.lower.text.luma() > main.lower.like.luma();
const hard = if dark { "area" } else { "like" };
const soft = if dark { "like" } else { "area" };

fn out() { `"#${this.to_hex_argb(true)}"` } // json

`{
	"metadata": {
		"name": "${cfg::display}",
		"revision": 1
	},
	
	"editor-colors": {
		"BackgroundColor": ${main.lower.area.out()},
		"BracketMatching": ${main.lower.text.fade(0.1).out()},
		"CodeFolding": "#224e65", ${/* FIXME */}
		"CurrentLine": ${main.lower.text.fade(0.1).out()},
		"CurrentLineNumber": ${main.lower.text.out()},
		"IconBorder": ${main.lower.like.out()},
		"IndentationLine": ${main.lower.text.fade(1.0 / 3).out()},
		"LineNumbers": ${main.lower.text.fade(0.625).out()},
		"MarkBookmark": ${main.blue.like.out()},
		"MarkBreakpointActive": "#8b0607", ${/* FIXME */}
		"MarkBreakpointDisabled": "#820683", ${/* FIXME */}
		"MarkBreakpointReached": "#6d6e07", ${/* FIXME */}
		"MarkError": ${main.red.like.out()},
		"MarkExecution": ${main.cyan.like.out()},
		"MarkWarning": ${main.yellow.like.out()},
		"ModifiedLines": ${main.any.area.out()},
		"ReplaceHighlight": "#808021", ${/* FIXME */}
		"SavedLines": ${main.green.area.out()},
		"SearchHighlight": ${main.magenta.like.fade(0.3).out()},
		"Separator": "${if dark { "#5F000000" } else { "#1F000000" }}",
		"SpellChecking": ${main.red.like.out()},
		"TabMarker": ${main.lower.text.fade(0.375).out()},
		"TemplateBackground": "#31363b", ${/* FIXME */}
		"TemplateFocusedPlaceholder": "#123723", ${/* FIXME */}
		"TemplatePlaceholder": "#123723", ${/* FIXME */}
		"TemplateReadOnlyPlaceholder": "#4d1f24", ${/* FIXME */}
		"TextSelection": ${main.lower.text.fade(0.15).out()},
		"WordWrapMarker": ${main.lower.text.fade(0.25).out()}
	},
	
	"text-styles": {
		"Alert": {
			"background-color": "#4d1f24", ${/* FIXME */}
			"bold": true,
			"selected-text-color": "#95da4c", ${/* FIXME */}
			"text-color": "#95da4c" ${/* FIXME */}
		},
		"Annotation": {
			"selected-text-color": ${main.green.like.out()},
			"text-color": ${main.green[hard].out()}
		},
		"Attribute": {
			"selected-text-color": ${main.any.like.out()},
			"text-color": ${main.any.area.out()}
		},
		"BaseN": {
			"selected-text-color": ${main.magenta.like.out()},
			"text-color": ${main.magenta.like.out()}
		},
		"BuiltIn": {
			"selected-text-color": ${main.magenta.like.out()},
			"text-color": ${main.magenta.like.out()}
		},
		"Char": {
			"selected-text-color": ${main.blue.like.out()},
			"text-color": ${main.blue.like.out()}
		},
		"Comment": {
			"selected-text-color": ${main.lower.text.out()},
			"text-color": ${main.lower.text.fade(0.625).out()}
		},
		"CommentVar": {
			"selected-text-color": ${main.lower.text.out()},
			"text-color": ${main.lower.text.out()}
		},
		"Constant": {
			"selected-text-color": ${main.magenta.like.out()},
			"text-color": ${main.magenta.like.out()}
		},
		"ControlFlow": {
			"italic": true,
			"selected-text-color": ${main.red.like.out()},
			"text-color": ${main.red.like.out()}
		},
		"DataType": {
			"selected-text-color": ${main.blue.like.out()},
			"text-color": ${main.blue.like.out()}
		},
		"DecVal": {
			"selected-text-color": ${main.magenta.like.out()},
			"text-color": ${main.magenta.like.out()}
		},
		"Documentation": {
			"selected-text-color": "#da4453", ${/* FIXME */}
			"text-color": "#a43340" ${/* FIXME */}
		},
		"Error": {
			"selected-text-color": "#da4453", ${/* FIXME */}
			"text-color": "#da4453", ${/* FIXME */}
			"underline": true
		},
		"Extension": {
			"selected-text-color": ${main.any.like.out()},
			"text-color": ${main.any.like.out()}
		},
		"Float": {
			"selected-text-color": ${main.magenta.like.out()},
			"text-color": ${main.magenta.like.out()}
		},
		"Function": {
			"selected-text-color": ${main.cyan.like.out()},
			"text-color": ${main.cyan.like.out()}
		},
		"Import": {
			"selected-text-color": ${main.magenta.like.out()},
			"text-color": ${main.magenta.like.out()}
		},
		"Information": {
			"selected-text-color": "#e46700", ${/* FIXME */}
			"text-color": "#c45b00" ${/* FIXME */}
		},
		"Keyword": {
			"selected-text-color": ${main.red[soft].out()},
			"text-color": ${main.red[soft].out()}
		},
		"Normal": {
			"selected-text-color": ${main.lower.text.out()},
			"text-color": ${main.lower.text.out()}
		},
		"Operator": {
			"selected-text-color": ${main.any.like.out()},
			"text-color": ${main.any.like.out()}
		},
		"Others": {
			"selected-text-color": ${main.green.like.out()},
			"text-color": ${main.green.like.out()}
		},
		"Preprocessor": {
			"selected-text-color": ${main.green.like.out()},
			"text-color": ${main.green.like.out()}
		},
		"RegionMarker": {
			"background-color": "#153042", ${/* FIXME */}
			"selected-text-color": "#3daee9", ${/* FIXME */}
			"text-color": "#2980b9" ${/* FIXME */}
		},
		"SpecialChar": {
			"selected-text-color": ${main.blue.like.out()},
			"text-color": ${main.blue.like.out()}
		},
		"SpecialString": {
			"selected-text-color": "#da4453", ${/* FIXME */}
			"text-color": "#da4453" ${/* FIXME */}
		},
		"String": {
			"selected-text-color": ${main.yellow[hard].out()},
			"text-color": ${main.yellow[hard].out()}
		},
		"Variable": {
			"selected-text-color": "#27aeae", ${/* FIXME */}
			"text-color": "#27aeae" ${/* FIXME */}
		},
		"VerbatimString": {
			"selected-text-color": ${main.green.like.out()},
			"text-color": ${main.green[hard].out()}
		},
		"Warning": {
			"selected-text-color": "#da4453", ${/* FIXME */}
			"text-color": "#da4453" ${/* FIXME */}
		}
	},
	
	"custom-styles": {
		"JavaScript": {
			"Objects": {
				"selected-text-color": ${main.blue.like.out()},
				"text-color": ${main.blue.like.out()}
			},
			"Substitution": {
				"selected-text-color": ${main.any.area.out()},
				"text-color": ${main.any.area.out()}
			}
		},
		"QML": {
			"Elements": {
				"selected-text-color": ${main.green.like.out()},
				"text-color": ${main.green.like.out()}
			}
		},
		"Rust": {
			"Scope": {
				"selected-text-color": ${main.magenta.like.out()},
				"text-color": ${main.magenta.like.out()}
			}
		},
		"TOML": {
			"Array": {
				"selected-text-color": ${main.lower.text.out()},
				"text-color": ${main.lower.text.out()}
			},
			"Assignment": {
				"selected-text-color": ${main.lower.text.out()},
				"text-color": ${main.lower.text.out()}
			},
			"InlineTable": {
				"selected-text-color": ${main.red[soft].out()},
				"text-color": ${main.red[soft].out()}
			},
			"NextEntry": {
				"selected-text-color": ${main.lower.text.out()},
				"text-color": ${main.lower.text.out()}
			}
		},
		"XML": {
			"Attribute": {
				"selected-text-color": ${main.magenta.like.out()},
				"text-color": ${main.magenta.like.out()}
			},
			"Attribute Separator": {
				"selected-text-color": ${main.blue.like.out()},
				"text-color": ${main.blue.area.out()}
			},
			"CDATA": {
				"selected-text-color": ${main.green.like.out()},
				"text-color": ${main.green.like.out()},
				"bold": false
			},
			"CDATA Symbols": {
				"selected-text-color": ${main.green.like.out()},
				"text-color": ${main.green.like.out()}
			},
			"Doctype": {
				"selected-text-color": ${main.green.like.out()},
				"text-color": ${main.green.like.out()},
				"bold": false
			},
			"Doctype Symbols": {
				"selected-text-color": ${main.any.area.out()},
				"text-color": ${main.any.area.out()}
			},
			"EntityRef": {
				"selected-text-color": ${main.any.like.out()},
				"text-color": ${main.any.like.out()}
			},
			"Element": {
				"selected-text-color": ${main.blue.like.out()},
				"text-color": ${main.blue.like.out()}
			},
			"Element Symbols": {
				"selected-text-color": ${main.magenta.like.out()},
				"text-color": ${main.magenta.area.out()}
			}
		}
	}
}`
'''
