# SPDX-FileCopyrightText: 2024 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name = 'KDE Syntax Highlighting'
type = 'text-file' # md
about = '''
A JSON file that provides a [color theme](https://docs.kde.org/trunk5/en/kate/katepart/color-themes.html)
for KDE's [Syntax Highlighting](https://api.kde.org/frameworks/syntax-highlighting/html/index.html)
framework, used by applications such as KWrite, Kate, and KDevelop.
''' # rhai

display = 'arrangement' # rhai
nomenclature = 'arrangement_id + ".theme"'

schemes.main.name = 'Main'

[suggested-paths]
default = { default = 'syntax_highlighting' }
user-1  = { data = 'org.kde.syntax-highlighting/themes' }
user-2  = { home = '.local/share/org.kde.syntax-highlighting/themes' }
