# SPDX-FileCopyrightText: 2024 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Unlicense

name  = 'Neon Cake Examples'
about = 'Using a parametric scheme'

[schemes]
     dark.request.scheme = 'neon-cake'
    light.request.scheme = 'neon-cake'
old-light.request.scheme = 'neon-cake'

[schemes.light.options]
name = 'Neon Cake Light'
overall-chroma    = 64.0
overall-luminance = 42.5
surface-luminance = 82.5
   text-luminance = 35.0

[schemes.old-light.options]
name = 'Neon Cake Light (Old)'
overall-luminance = 35.0
surface-luminance = 82.5
   text-luminance = 35.0
